:caps:
  testName: 'Demo Android Automation'
  accessKey: ""
  deviceQuery: "@os='android' and @version='11.0' and @category='PHONE'"
  app: "cloud:com.ebay.mobile/.activities.MainActivity"
  platformName: "Android"
  appPackage: "com.ebay.mobile"
  appActivity: "com.ebay.mobile.activities.MainActivity"
  releaseVersion: ""
  fullReset: false
  automationName: "UiAutomator2"
  autoWebView: true
  setWebContentsDebuggingEnabled: true
  autoAcceptAlerts: true
  locationServicesEnabled: true
  autoGrantPermissions: true
  newCommandTimeout: 800
  appiumVersion: 1.22.2

:appium_lib:
  server_url: ""

